name: NodeJS

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: 'npm'

            - name: Dependencies
              run: npm ci

            - name: test
              run: npm run test
