name: NodeJS

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts

      - name: Dependencies
        run: npm ci

      - name: test
        run: npm run test
